version: "3.8"
services:
  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
  flight-service:
    image: flight-service:compose_build
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8080
      DATABASE_NAME: XWS
      JWT_SECRET: secret
      DATABASE_CONNECTION_STRING: mongodb+srv://xws:lozinka123@cluster0.yqfgbck.mongodb.net/?retryWrites=true&w=majority

  auth-service:
    image: auth-service:compose_build
    build:
        context: ./auth-service
        dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8080
      DATABASE_NAME: AUTH
      JWT_SECRET: secret
      DATABASE_CONNECTION_STRING: mongodb+srv://xws:lozinka123@cluster0.yqfgbck.mongodb.net/?retryWrites=true&w=majority
networks:
  backend:
    driver: bridge
